---
# install main programm
- hosts: all
  gather_facts: no
  tasks:
  - shell: ip addr
    register: res1
  - shell: |
      echo '{{res1.stdout}}' > remote.ip_addr.txt
    delegate_to: localhost
#
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - shell: ls / > local_root_files.txt
      
